path:
  # 资源文件夹，存放每个模块的样式文件
  source: ./src/main/resources/css/
  # 输出文件，打包后的输出
  out: ./src/main/resources/out/main.css
# 匹配模式，对应stylus的4种模式，仅仅为了复制方便，没有其他用途
match-mode:
  # 域名
  domain: domain
  # 固定url
  url: url
  # url前缀
  url-prefix: url-prefix
  # 正则
  regexp: regexp
# 资源文件配置
configs:
  # 注释，打包为一个文件后的说明
  - note: md颜色
    # 对应文件名称
    file-name: mdColor.css
    # 匹配网址的方式
    matches:
      # 匹配模式
      - mode: domain
        # 对应模式下的参数
        params:
          - keylol.com
  - note: 变量配置
    # 测试时启用此文件，对应的参数
#    file-name: var.css
    # 正式打包时使用此文件
    file-name: optional.txt
    matches:
      - mode: domain
        params:
          - keylol.com
  - note: 导航栏
    file-name: nav.css
    matches:
      - mode: domain
        params:
          - keylol.com
  - note: 首页
    file-name: home.css
    matches:
      - mode: regexp
        params:
          - "https?://keylol.com/(forum.php)?"
  - note: 帖子内容
    file-name: post.css
    matches:
      - mode: url-prefix
        params:
          - https://keylol.com/t
          - https://keylol.com/forum.php?mod=viewthread&t
  - note: 板块（帖子列表）
    file-name: postList.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com/f[0-9][0-9][0-9].+"
          - ".+keylol.com.+forumdisplay.+fid=[0-9]+.+"
  - note: 导读
    file-name: guide.css
    matches:
      - mode: url-prefix
        params:
          - http://keylol.com/forum.php?mod=guide
          - https://keylol.com/forum.php?mod=guide
  - note: 导读的“最新热门”、“最新回复”、“最新发表”、“我的帖子”
    file-name: guide-new-hot-my.css
    matches:
      - mode: url-prefix
        params:
          - http://keylol.com/forum.php?mod=guide
          - https://keylol.com/forum.php?mod=guide
  - note: 导读的“最新精华”、“抢沙发”
    file-name: guide-digest-sofa.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com.+mod=guide&view=(digest|sofa)"
  - note: 导读的“我的帖子”
    file-name: guide-my.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com.+mod=guide&view=my"
  - note: 通知
    file-name: notification.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com.+mod=space&do=(pm|notice(&view=.*)?).*"
  - note: 页脚
    file-name: foot.css
    matches:
      - mode: domain
        params:
          - keylol.com
  - note: 高级编辑框
    file-name: new-thread.css
    matches:
      - mode: regexp
        params:
          - ".+keylol.com.+mod=post&action=(newthread|reply|edit).*"